name: Build Android

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: npm install

      - name: Generate native project
        run: npx expo prebuild --platform android --non-interactive

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Get app version
        id: app_version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: chinchon-${{ steps.app_version.outputs.version }}.apk
          path: android/app/build/outputs/apk/release/app-release.apk
